trigger:
  branches:
    include:
      - main  # Change this to your default branch if needed

pool:
  vmImage: 'ubuntu-latest'  # Choose the image you need, e.g., ubuntu-latest, windows-latest, etc.

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # Specify Python version (e.g., 3.x or 3.9)
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install pytest  # Install pytest
  displayName: 'Install dependencies'

- script: |
    pytest  # Run the tests
  displayName: 'Run Tests'
